### ISSUE TITLE
return of overlap_values

### ISSUE THREAD

**Issue by DRKWang** [kip-hart/AABBTree#15]
Thanks for your help in adding an option for boundary intersection detection, which is quite essential in my project. In fact, I also have another request for adding an option for the return value of the `overlap_values()` method.

I can understand that you add the following function
```
def _unique_pairs(pairs):    
      boxes, _ = zip(*pairs)    
      u_pairs = [p for i, p in enumerate(pairs) if p[0] not in boxes[:I]]    
      return u_pair
```
 to avoid duplication boxes and keep the output succinct as much as possible. But, it seems not consistent with the return of `overlap_values()`.
For example, 

```
from aabbtree import AABB
from aabbtree import AABBTree 
tree = AABBTree()
aabb1 = AABB([(0, 1)])
aabb2 = AABB([(0, 1)])
aabb3 = AABB([(0, 1)])
tree.add(aabb1, 'box 1')
tree.add(aabb2, 'box 2')
tree.overlap_values(aabb3)
>>>['box 1']
```

In this scenario, we take the AABBtree as a dictionary to retrieve, sort of like a key-value dictionary. Those 3 boxes are identical in terms of geometrical coordinates, but, they are not identical in terms of value. Thus, logically, they are different. And if we want to know which boxes have an intersection with the target box, it is going to be expected to return all of them in some cases. Besides, if we only return one `['box 1']`, it is not fair for `'box 2'`. 

Could you add an optional flag to specify whether it will return `one` or `all` boxes, something similar things like that?

Thanks!

**Comment by DRKWang** [comment]
By the way, I also have an extra question about the balancing method of the AABB tree. Recently, I am working on my project by using your implementation for the AABB tree. It is quite well right now in terms of accuracy and runtime, but after several experiments, I found the depth of the AABB tree sometimes could be extremely long, which indicates that the AABB tree degenerates into almost a chain in some sense. I think it will lose the advantage of the AABB tree when it comes into a chain. So, currently, I am hoping to get rid of that bad situation, but I am not sure which one causes it, input data, or the balancing method for the AABB tree? I saw there are a few ways to balance an AABB tree, but I am not sure which one is used here for it?

**Comment by kip-hart** [comment]
Hi @DRKWang I've created a branch with the option to return duplicate AABBs and their values from the tree.

For balance, have you tried both `method='DFS'` and `method='BFS'`?

I wrote the package initially for myself, used in another package where the bounds of box "i" depended on the bounds of boxes 0 to "i-1". I needed an incremental insertion method, but there's also top-down and bottom-up methods. The `AABBTree.add` method is incremental and attempts to add nodes to an existing tree, in a balanced way, by minimizing a heuristic. This is the best it can do when nodes are added incrementally, but the top-down and bottom-up methods are better when all the boxes a are already defined.

I didn't need top-down or bottom-up methods when I initially wrote the package, but they're certainly useful. Would you be willing to look into these methods and submit a PR to add that functionality? I can help out, but I won't have time to code it myself in the next 6 months.

**Comment by kip-hart** [comment]
The option to return non-unique AABBs and their values has been added in v2.8.0.

**Comment by DRKWang** [comment]
> Hi @DRKWang I've created a branch with the option to return duplicate AABBs and their values from the tree.
> 
> ~For balance, have you tried both `method='DFS'` and `method='BFS'`?~
> 
> I wrote the package initially for myself, used in another package where the bounds of box "i" depended on the bounds of boxes 0 to "i-1". I needed an incremental insertion method, but there's also top-down and bottom-up methods. The `AABBTree.add` method is incremental and attempts to add nodes to an existing tree, in a balanced way, by minimizing a heuristic. This is the best it can do when nodes are added incrementally, but the top-down and bottom-up methods are better when all the boxes are already defined.
> 
> I didn't need top-down or bottom-up methods when I initially wrote the package, but they're certainly useful. Would you be willing to look into these methods and submit a PR to add that functionality? I can help out, but I won't have time to code it myself in the next 6 months.

Thanks for your help in adding the optional return of duplicate AABBs for me! It will be honorable for me to submit a PR and add that functionality. Perhaps, there be several ways to construct an AABB tree, so it would take a little time to program, but I would like to continuously update it.

**Comment by kip-hart** [comment]
Hi @DRKWang have you worked on this over the last year? If not, I'll close the issue.
