### ISSUE TITLE
issue with values saved in AABBTree

### ISSUE THREAD

**Issue by maomaozi** [kip-hart/AABBTree#17]
Hi, thanks for providing such a great project, it really helped me a lot. But I recently found in some cases, the return value of the overlap_values have some problems for me. Mainly for the value of the 'object type', a copy of it is returned instead of the original value I passed in.

For example:

```
if __name__ == '__main__':
    tree = AABBTree()
    foo_list = [Foo() for i in range(5)]

    for foo in foo_list:
        tree.add(AABB([(0, 1), (0, 1)]), value=foo)

    new_foo_list = tree.overlap_values(AABB([(0, 1), (0, 1)]), unique=False)

    print(foo_list)
    print(new_foo_list)
```

the output is:
```
[<__main__.Foo object at 0x10f30d5e0>, <__main__.Foo object at 0x10f33de80>, <__main__.Foo object at 0x10f3fc820>, <__main__.Foo object at 0x10f3fca00>, <__main__.Foo object at 0x10f3fc970>]
[<__main__.Foo object at 0x10f448e50>, <__main__.Foo object at 0x10f453250>, <__main__.Foo object at 0x10f4535b0>, <__main__.Foo object at 0x10f453910>, <__main__.Foo object at 0x10f3fc970>]
```

It seems cause by the deepcopy in add function:

```
        elif self.is_leaf:
            self.left = copy.deepcopy(self)
```
AND
```
            if branch_cost < left_cost and branch_cost < right_cost:
                self.left = copy.deepcopy(self)
```

I have done some workarounds in my project and it seems to work, I think the deepcopy here may not be necessary(and may have additional overhead for large value objects or deep branch), just create a new AABBTree here and simply move all the properties to the new one, then assign it to self.left may work as well

**Comment by kip-hart** [comment]
Hi, thank you for your feedback on the project and looking into the memory usage. Would you be willing to submit a PR with shallow copies instead of deep copies?

**Comment by kip-hart** [comment]
Thanks for contributing the update!
