### ISSUE TITLE
return bounding boxes

### ISSUE THREAD

**Issue by krober10nd** [kip-hart/AABBTree#4]
Hey, 

Is is possible to return the corners of the bounding box for each leaf? I would like to use the decomposition of an input point set in another algorithm.

Thanks!

**Comment by kip-hart** [comment]
Hi @krober10nd ,

Yes, it is possible. Each leaf contains an instance of the AABB class, which has the attribute limits. The corners can be derived from the limits using a function like this:

```python
def limits2corners(limits):
    n_dim = len(limits)
    f = '{:0' + str(n_dim) + 'b}'

    n_corners = 2 ** n_dim
    corners = []
    for i in range(n_corners):
        inds = [int(s) for s in f.format(i)]  # convert i to list of 0s and 1s
        corner = [limits[ind] for ind in inds]
        corners.append(corner)
    return corners
```

I could add this as a property of the AABB class, then the corners of each leaf would be in `self.aabb.corners` for the leaf. Would that work?

**Comment by krober10nd** [comment]
Yes that would help! Thanks for that!

**Comment by kip-hart** [comment]
I added the `corners` property to the AABB class and updated to version 2.4.0. Thanks for the suggestion! Let me know if there are other features I could add.
