### ISSUE TITLE
Getting boundaries of the overlaps

### ISSUE THREAD

**Issue by LumaEmu** [kip-hart/AABBTree#5]
Hi! Is there any method to actually get the boundaries or of the overlapping boxes inside a tree?
Now I can use the "does_overlap(aabb_obj)" method of the AABBTree to check for overlaps but it says nothing about the exact box which overlaps given aabb_obj, only "yes/no" answer.

Or maybe return the AABBTree object with an overlapping box as a root of subtree would be a nice solution.

Thanks.

**Comment by kip-hart** [comment]
Sorry for the delayed response. I am added an `overlap_aabbs` function in addition to the `overlap_values` function to do just this.
